### ISSUE TITLE
[QnA] Rendering 2 Questions at a time Part 1.

### ISSUE THREAD

**Issue by justjjasper** [Nugget-Reactor/FEC#67]
https://github.com/Nugget-Reactor/FEC/blob/0e5934a3bb49fa218f840e9b56deafb12b011081/client/src/Components/QnA/QuestionsList.jsx#L22-L42

You're able to refactor the QuestionListBody(Lines 25-35) by removing the ternary operator, the else section (Lines 32-Lines 34) isn't necessary. (I'm aware the else logic is to load the rest of the ?'s ONCE you're able to display all of your ?'s)

However, if you just change it to a regular conditional render and add one more Or Operator to the condition, you should be able to handle both cases where the questions would render properly under the "load by 2 questions at a time" and loading all of the questions once you hit the end of your list.
  - The Condition I was referring to is line 26, where you want the ```currCount``` to be less than/equal to ```totalCount``` **OR OPERATOR** ```currCount``` is equal to ```totalCount + 1```

As a reminder, ```totalCount``` is the length of the questions list, so the newly added condition where ```currCount``` is equal to ```totalCount+``` is to handle the scenario if ```currCount``` exceeds ```totalCount``` during the logic through your ```handleMoreAs(e)``` logic.

**Comment by cwang1014** [comment]
This ended up bringing me down a bit of a rabbit hole! I noticed my questions list was resetting to the shortened version only displaying 2 entries when I submitted a new question and thought it was because of a change I made in the conditional rendering, but I realized it was a problem with my useEffect firing and resetting the current count which was resetting my list. I had to create another state to track if it was a new product changing the list or not, to be able to have a conditional inside useEffect to check if it should reset the list when rerendering the new question or simply add to the extended list.

Super appreciate your detailed explanation and breakdown. Thanks so much!!
